resource_list ::= '[' resource (',' resource)* ']'

resource ::= '[' resource_type ',' '{' properties '}' (','  '[' resource (',' resource )* ']' )? ']'  

resource_type ::= 'menu' | 'msg' | 'uri' | 'instance' | 'validation'

properties ::= ('{' (menu_property | msg_property | uri_property | instance_property | validation_property) ':' value '}')+

menu_property ::=  'title' | 'description' | 'name' | 'items'

uri_property ::= 'title' | 'description' | 'url'

msg_property ::= 'title' | 'description'

instance_property ::= 'name' | 'uri' | 'new_rec' | 'search' | 'schema' | 'instance_get_actions'

validation_property ::= string_literal

title_value ::= string_literal

description_value ::= string_literal

name_value ::= string_literal

items_value ::= '[' resource (',' resource)? ']'

new_rec_value ::= boolean_value

search_value ::= boolean_value

schema_value ::= '[' col_spec (',' colspec)? ']'

instance_get_actions ::= '[' action (',' action)*']'

action ::= string_value

col_spec ::= '[' col_type ',' col_name ',' col_restrictions (',' col_value)?  ']'

col_type ::= 'text' | 'clob' | 'integer' | 'decimal' | 'image' 

col_name ::= string_literal

col_restrictions ::= [1-7]

col_value ::= string_literal

